train: /home/axldvd/Documents/projects/ebs-ai/src/data/train/images
val: /home/axldvd/Documents/projects/ebs-ai/src/data/valid/images
test: /home/axldvd/Documents/projects/ebs-ai/src/data/test/images

nc: 77
names: ['Air-Conditioner', 'Bar-Phone', 'Battery', 'Blood-Pressure-Monitor', 'Boiler', 'CRT-Monitor', 'CRT-TV', 'Calculator', 'Camera', 'Ceiling-Fan', 'Christmas-Lights', 'Clothes-Iron', 'Coffee-Machine', 'Compact-Fluorescent-Lamps', 'Computer-Keyboard', 'Computer-Mouse', 'Cooled-Dispenser', 'Cooling-Display', 'Dehumidifier', 'Desktop-PC', 'Digital-Oscilloscope', 'Dishwasher', 'Drone', 'Electric-Bicycle', 'Electric-Guitar', 'Electrocardiograph-Machine', 'Electronic-Keyboard', 'Exhaust-Fan', 'Flashlight', 'Flat-Panel-Monitor', 'Flat-Panel-TV', 'Floor-Fan', 'Freezer', 'Glucose-Meter', 'HDD', 'Hair-Dryer', 'Headphone', 'LED-Bulb', 'Laptop', 'Microwave', 'Music-Player', 'Neon-Sign', 'Network-Switch', 'Non-Cooled-Dispenser', 'Oven', 'PCB', 'Patient-Monitoring-System', 'Photovoltaic-Panel', 'PlayStation-5', 'Power-Adapter', 'Printer', 'Projector', 'Pulse-Oximeter', 'Range-Hood', 'Refrigerator', 'Rotary-Mower', 'Router', 'SSD', 'Server', 'Smart-Watch', 'Smartphone', 'Smoke-Detector', 'Soldering-Iron', 'Speaker', 'Stove', 'Straight-Tube-Fluorescent-Lamp', 'Street-Lamp', 'TV-Remote-Control', 'Table-Lamp', 'Tablet', 'Telephone-Set', 'Toaster', 'Tumble-Dryer', 'USB-Flash-Drive', 'Vacuum-Cleaner', 'Washing-Machine', 'Xbox-Series-X']
names:
{
  'Air-Conditioner': 0,
  'Bar-Phone': 1,
  'Battery': 2,
  'Blood-Pressure-Monitor': 3,
  'Boiler': 4,
  'CRT-Monitor': 5,
  'CRT-TV': 6,
  'Calculator': 7,
  'Camera': 8,
  'Ceiling-Fan': 9,
  'Christmas-Lights': 10,
  'Clothes-Iron': 11,
  'Coffee-Machine': 12,
  'Compact-Fluorescent-Lamps': 13,
  'Computer-Keyboard': 14,
  'Computer-Mouse': 15,
  'Cooled-Dispenser': 16,
  'Cooling-Display': 17,
  'Dehumidifier': 18,
  'Desktop-PC': 19,
  'Digital-Oscilloscope': 20,
  'Dishwasher': 21,
  'Drone': 22,
  'Electric-Bicycle': 23,
  'Electric-Guitar': 24,
  'Electrocardiograph-Machine': 25,
  'Electronic-Keyboard': 26,
  'Exhaust-Fan': 27,
  'Flashlight': 28,
  'Flat-Panel-Monitor': 29,
  'Flat-Panel-TV': 30,
  'Floor-Fan': 31,
  'Freezer': 32,
  'Glucose-Meter': 33,
  'HDD': 34,
  'Hair-Dryer': 35,
  'Headphone': 36,
  'LED-Bulb': 37,
  'Laptop': 38,
  'Microwave': 39,
  'Music-Player': 40,
  'Neon-Sign': 41,
  'Network-Switch': 42,
  'Non-Cooled-Dispenser': 43,
  'Oven': 44,
  'PCB': 45,
  'Patient-Monitoring-System': 46,
  'Photovoltaic-Panel': 47,
  'PlayStation-5': 48,
  'Power-Adapter': 49,
  'Printer': 50,
  'Projector': 51,
  'Pulse-Oximeter': 52,
  'Range-Hood': 53,
  'Refrigerator': 54,
  'Rotary-Mower': 55,
  'Router': 56,
  'SSD': 57,
  'Server': 58,
  'Smart-Watch': 59,
  'Smartphone': 60,
  'Smoke-Detector': 61,
  'Soldering-Iron': 62,
  'Speaker': 63,
  'Stove': 64,
  'Straight-Tube-Fluorescent-Lamp': 65,
  'Street-Lamp': 66,
  'TV-Remote-Control': 67,
  'Table-Lamp': 68,
  'Tablet': 69,
  'Telephone-Set': 70,
  'Toaster': 71,
  'Tumble-Dryer': 72,
  'USB-Flash-Drive': 73,
  'Vacuum-Cleaner': 74,
  'Washing-Machine': 75,
  'Xbox-Series-X': 76
}
roboflow:
  workspace: electronic-waste-detection
  project: e-waste-dataset-r0ojc
  version: 44
  license: CC BY 4.0
  url: https://universe.roboflow.com/electronic-waste-detection/e-waste-dataset-r0ojc/dataset/44