"""
Pydantic response models for API endpoints

Pipeline Flow: YOLO Detection → Gemini Validation → YOLO-to-Price Mapping → Price Prediction
- YOLO categories: 37 classes (Phone, Laptop, etc.)
- Price categories: 33 classes (Handphone, Laptop, etc.)
- Final response shows validated YOLO categories with price predictions
"""

from typing import List, Optional
from pydantic import BaseModel, Field


class Detection(BaseModel):
    """Single YOLO object detection result"""
    id: str = Field(..., description="Unique detection ID")
    category: str = Field(..., description="YOLO detected category (37 classes)")
    confidence: float = Field(..., description="YOLO detection confidence (0-1)")
    bbox: List[float] = Field(..., description="Bounding box coordinates [x1, y1, x2, y2]")


class PriceResponse(BaseModel):
    """Price prediction response for price model categories"""
    category: str = Field(..., description="Price model category name (33 classes)")
    price: int = Field(..., description="Estimated price in IDR")


class ObjectResponse(BaseModel):
    """YOLO detection response - raw detections without validation"""
    detections: List[Detection] = Field(..., description="List of YOLO detected objects")


class FullPrediction(BaseModel):
    """Complete prediction after full pipeline processing"""
    id: str = Field(..., description="Unique prediction ID")
    category: str = Field(..., description="Final validated category (YOLO category after Gemini validation)")
    confidence: float = Field(..., description="Original YOLO detection confidence")
    regression_result: Optional[int] = Field(None, description="Price prediction in IDR (from mapped price category)")
    description: str = Field(..., description="Visual description of e-waste item (max 20 words)")
    bbox: List[float] = Field(..., description="Bounding box coordinates [x1, y1, x2, y2]")
    suggestion: List[str] = Field(..., description="Disposal suggestions (3 items)")
    risk_lvl: int = Field(..., description="Environmental/health risk level 1-10")
    damage_level: Optional[int] = Field(None, description="Damage level 1-10 (1=Excellent, 10=Severe) - Generated by Gemini AI")
    detection_source: str = Field(..., description="Source: 'YOLO' or 'Gemini Interfered'")


class FullResponse(BaseModel):
    """Complete analysis response after full pipeline"""
    predictions: List[FullPrediction] = Field(..., description="Complete predictions with validation and pricing")


class ValidationResult(BaseModel):
    """Gemini YOLO validation result"""
    is_valid: bool = Field(..., description="Whether detection is valid e-waste")
    final_category: Optional[str] = Field(None, description="Final YOLO category after validation")
    detection_source: str = Field(..., description="Source of final decision: 'YOLO' or 'Gemini Interfered'")
    gemini_feedback: str = Field(..., description="Gemini reasoning or error message")
